### ISSUE TITLE
Suggest we add a brief "If all went well..." statement to the end of the README walkthrough.

### ISSUE THREAD

**Issue by gregcurfman** [cfsworkload/gameon-room-go#1]
The current readme walkthrough ends rather abruptly with the IP address binding.  I suggest that we add a brief statement about the room now being available for use.

A suggested ending has been added in the branch issue.001.README, commit 0eea2bfee27e9935ddcf5376a88c8d193f52874c.

**Comment by jsamnIBM** [comment]
Added in commit a6445a252d42c5a7afcc00e82f25ade7ba64699e
